### ISSUE TITLE
Error installing on Raspberry PI Zero W

### ISSUE THREAD

**Issue by pacoferre** [veyeimaging/raspberrypi_v4l2#1]
Hello, perhaps the folder naming is not correct on driver_bin.

pi@raspberrypi:~/raspberrypi_v4l2/release $ sudo ./install_driver.sh veye327

usage: sudo ./install_driver.sh veye327/csimx307/cssc132

Enable i2c0 adapter...

Add dtoverlay=veye327 to /boot/config.txt

Add gpu=400M to /boot/config.txt
Add cma=128M to /boot/cmdline.txt

Installing the veye327.ko driver

install: cannot stat './driver_bin/5.4.83+/veye327.ko': No such file or directory
install: cannot stat './driver_bin/5.4.83+/veye327.dtbo': No such file or directory
reboot now?(y/n):

**Comment by bleara** [comment]
There isn't a December (RPi kernel 5.4.83) version for the Zero or B+ yet.
For the Pi2B & Pi3 and Pi 4 you need to rename the files 5.4.83-v7+_20210111 to 5.4.83-v7+ and 5.4.83-v7l+_20210111 to 5.4.83-v7l+ before you run the install. I had the same problem but it works for me on these platforms.

**Comment by pacoferre** [comment]
Thanks a lot @bleara, sorry for the late reply.

I just took a Raspberry PI 4 and the driver installed correctly, now I'm having another issue regarding exposure.
