### ISSUE TITLE
Installation/Compilation fails on 64bit kernel

### ISSUE THREAD

**Issue by Modac** [veyeimaging/raspberrypi_v4l2#11]
It seems the newest Raspberry Pi OS 32bit versions use the 64bit kernel but the v8+/build directory is missing, so I had to add `arm_64bit=0` to `/boot/config.txt` and reboot so that the v7l+/build directory is used. As said [here](https://forums.raspberrypi.com/viewtopic.php?t=350269).
I think it would be helpful to add some hint for this in the README?

**Comment by mmxuxp** [comment]
Thank you for your suggestion, I will update it right away.
Also my response on github is not fast enough, feel free to communicate at forum.veye.cc.
