### ISSUE TITLE
What to do with drivers after compilation on Raspberry?

### ISSUE THREAD

**Issue by standmit** [veyeimaging/raspberrypi_v4l2#12]
The "Building Locally" chapter ended unexpectedly. I have compile drivers and dts. What next?

**Comment by etale-cohomology** [comment]
Same question here.

**Comment by zoldaten** [comment]
put `em (dtbo) to /boot/overlays

see also - https://bootlin.com/blog/enabling-new-hardware-on-raspberry-pi-with-device-tree-overlays/

**Comment by mmxuxp** [comment]
Has updated the document.
Please refer to part 3:
https://wiki.veye.cc/index.php/Build_drivers_from_source_for_rpi
