### ISSUE TITLE
树莓派4b_32位_内核Linux5.10_imx462LRC 编译报错

### ISSUE THREAD

**Issue by xiaxiamy** [veyeimaging/raspberrypi_v4l2#14]
您好， 我在树莓派4b_32位_内核Linux5.10版本_imx462LRC 的开发环境上需要编译v4l2，进入到5.x.all路径后，执行make指令, 报错信息如下：
![t1](https://github.com/user-attachments/assets/9f9ed51c-066b-41ee-a28c-261efd338431)
![t2](https://github.com/user-attachments/assets/6c27dfdf-5537-4c2e-a086-e938e2214d85)
请帮忙看看是哪里的问题，多谢！

**Comment by mmxuxp** [comment]
请参考最新updte的代码再编译一下即可。
