### ISSUE TITLE
Error on RPi4

### ISSUE THREAD

**Issue by powerfischiMF** [veyeimaging/raspberrypi_v4l2#4]
installing now worked, but I get the following error:

pi@raspberrypi:~ $ dmesg | grep veye
[    5.708555] veye327: disagrees about version of symbol module_layout
[    5.728882] veye327: disagrees about version of symbol module_layout
[    5.749376] veye327: disagrees about version of symbol module_layout
[   31.834579] veye327_vddl: disabling
[   31.834601] veye327_vdig: disabling
[   31.834626] veye327_vana: disabling

**Comment by jenyak** [comment]
I had this problem when I used the old version of the driver 5.4.83-v7+ in the newer kernel 5.10.17-v7l+.
The solution was to recompile the driver for new kernel as described in [wiki](http://wiki.veye.cc/index.php/V4L2_mode_for_Raspberry_Pi#Source_code_cross_compilation).
[This is a veye327 driver for kernel 5.10.17-v7l+](https://www.sendgb.com/3dHGMZeB1Cb)

**Comment by mmxuxp** [comment]
have 5.10.17 version now.
